<?php
require_once 'vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer();

$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = 'e9f57fc7885f9d'; //paste one generated by Mailtrap
$mail->Password = '706849f9ee5bc6'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525;

$mail->setFrom('9962c62253-14fc3c@inbox.mailtrap.io', 'Mailtrap');
$mail->addReplyTo('9962c62253-14fc3c@inbox.mailtrap.io', 'Mailtrap');
$mail->addAddress('jakub.vavru@student.ossp.cz', 'Tim');
$mail->Subject = 'Test Email via Mailtrap SMTP using PHPMailer';

$mail->isHTML(true);

$mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
    <p>This is a test email I’m sending using SMTP mail server with PHPMailer.</p>";
$mail->Body = $mailContent;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
if($mail->send()){
    echo 'Message has been sent';
}else{
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}
    ?>
</body>
</html>